### ISSUE TITLE
Series02 Check

### ISSUE THREAD

**Issue by bethccore** [SBOHVM/FernandaSanchezRSeries02#2]
Everything is looking grand! All files compile and the code/graphs are displayed nicely! I particularly liked how thorough you were in the set up of contents at the beginning of each file. 

It would be a bonus if you could maybe put your plot analysis on 0201-run in bold or as a sub-sub-heading or something so that it's a bit clearer, like you did in some of the later 'run' files. You could also maybe play around a bit more with overlapping the graphs in 0202-test to compare the time steps a bit more graphically. I highly doubt these are necessary adaptions, it was just if you wanted to make it 'even better', all the files already look really good! :) Well done, it's very impressive!

**Comment by FernandaSanchezR** [comment]
Thank you!! I will try to incorporate your suggestions :)
